mediawiki-restore (14)

diff --git a/backup-system/mediawiki-restore b/backup-system/mediawiki-restore
--- a/backup-system/mediawiki-restore
+++ b/backup-system/mediawiki-restore
@@ -75,8 +75,6 @@ function restore-mediawiki() {
   restore-database "${backup_dir}" "${database_root_password}"
   restore-local-settings "${backup_dir}" "${target_mediawiki_dir}"
   restore-image-files "${backup_dir}" "${target_mediawiki_dir}"
-  restore-skins "${backup_dir}" "${target_mediawiki_dir}"
-  restore-extensions "${backup_dir}" "${target_mediawiki_dir}"
   restore-certificates-and-keys "${backup_dir}"
   manual-post-install-warning "${backup_dir}"
 }
@@ -233,6 +231,29 @@ function restore-image-files() {
   info "$(basename ${target_image_dir}) directory restored"
 }
 
+function restore-certificates-and-keys() {
+
+  debug "${FUNCNAME[0]}($*)"
+  local backup_dir=$1
+  [[ -z ${backup_dir} ]] && fail "'backup_dir' not provided"
+
+  local source_dir=${backup_dir}/etc/pki/tls/certs
+  [[ -d ${source_dir} ]] || fail "no certificate directory found in ${backup_dir}: ${source_dir}"
+  cp ${source_dir}/*.crt /etc/pki/tls/certs || fail "failed to copy ${source_dir}/*.crt to /etc/pki/tls/certs"
+
+  local source_dir=${backup_dir}/etc/pki/tls/private
+  [[ -d ${source_dir} ]] || fail "no key directory found in ${backup_dir}: ${source_dir}"
+  for i in ${source_dir}/*.key; do
+    cp ${i} /etc/pki/tls/private || fail "failed to copy ${i} to /etc/pki/tls/private"
+    chmod go-rwx /etc/pki/tls/private/$(basename ${i}) || fail "failed to chmod /etc/pki/tls/private/$(basename ${i})"
+  done
+  info "certificates and private keys restored in /etc/pki/tls"
+}
+
+#
+# Normally should not be used, as we do not want to backup and restore skins, but use the new ones that come with the
+# new version.
+#
 function restore-skins() {
 
   debug "${FUNCNAME[0]}($*)"
@@ -255,6 +276,10 @@ function restore-skins() {
   done
 }
 
+#
+# Normally should not be used, as we do not want to backup and restore extensions, but install the up-to-date extensions
+# from scratch in top of the new version
+#
 function restore-extensions() {
 
   debug "${FUNCNAME[0]}($*)"
@@ -277,25 +302,6 @@ function restore-extensions() {
   done
 }
 
-function restore-certificates-and-keys() {
-
-  debug "${FUNCNAME[0]}($*)"
-  local backup_dir=$1
-  [[ -z ${backup_dir} ]] && fail "'backup_dir' not provided"
-
-  local source_dir=${backup_dir}/etc/pki/tls/certs
-  [[ -d ${source_dir} ]] || fail "no certificate directory found in ${backup_dir}: ${source_dir}"
-  cp ${source_dir}/*.crt /etc/pki/tls/certs || fail "failed to copy ${source_dir}/*.crt to /etc/pki/tls/certs"
-
-  local source_dir=${backup_dir}/etc/pki/tls/private
-  [[ -d ${source_dir} ]] || fail "no key directory found in ${backup_dir}: ${source_dir}"
-  for i in ${source_dir}/*.key; do
-    cp ${i} /etc/pki/tls/private || fail "failed to copy ${i} to /etc/pki/tls/private"
-    chmod go-rwx /etc/pki/tls/private/$(basename ${i}) || fail "failed to chmod /etc/pki/tls/private/$(basename ${i})"
-  done
-  info "certificates and private keys restored in /etc/pki/tls"
-}
-
 function manual-post-install-warning() {
 
   debug "${FUNCNAME[0]}($*)"
@@ -308,9 +314,8 @@ function manual-post-install-warning() {
   warn "continue with manual post-restore steps:"
   warn " - if this was an upgrade to a newer MediaWiki version, run php update in /var/www/mediawiki-*/maintenance"
   warn " - configure the Listen directive and the virtual host (./ssl.conf) in /etc/httpd/conf.d/ssl.conf"
+  warn " - re-install the following extensions: TODO"
   warn ""
 }
 
-#VERBOSE=true
-#backup-dir-to-mediawiki-dir $1
 main "$@"
