final warning

diff --git a/backup-system/mediawiki-restore b/backup-system/mediawiki-restore
--- a/backup-system/mediawiki-restore
+++ b/backup-system/mediawiki-restore
@@ -18,7 +18,7 @@ The script will interactively request the MySQL root account password.
 
 Usage:
 
-  $(basename $0) <backup-file> <mediawiki-installation-dir>
+  $(basename $0) <backup-file> <mediawiki-installation-dir> [-d|--post-install-dir post-installation-examples-dir]
 
 Arguments:
 
@@ -28,6 +28,9 @@ Arguments:
     is installed (by default /var/www/mediawiki-<version>).
 
 Options:
+
+ -d|--post-install-dir <post-installation-examples-dir> - the directory where the post-installation examples are
+    written. If not specified the local directory is used to store the examples.
 
  -p|--preserve-tmp Optional boolean flag that instructs the program to preserve the temporary directory.
 
@@ -44,6 +47,7 @@ function main() {
   declare -a ARGS
   declare -A OPTIONS
   OPTIONS["--preserve-tmp"]="boolean -p"
+  OPTIONS["--post-install-dir"]="string -d"
   process-options "$@"
   fail-on-unknown-arguments 2
 
@@ -51,7 +55,7 @@ function main() {
   tmp_dir=$(get-tmp-dir) || exit 1
   trap "mediawiki-cleanup ${tmp_dir} ${OPTIONS[--preserve-tmp]}" EXIT
 
-  restore-mediawiki "${ARGS[0]}" "${ARGS[1]}" "${tmp_dir}"
+  restore-mediawiki "${ARGS[0]}" "${ARGS[1]}" "${tmp_dir}" "${OPTIONS[--post-install-dir]}"
 }
 
 function restore-mediawiki() {
@@ -60,10 +64,14 @@ function restore-mediawiki() {
   local backup_file=$1
   local target_mediawiki_dir=$2
   local tmp_dir=$3
+  local post_installation_examples_dir=$4
 
   debug "backup_file: ${backup_file}"
   debug "target_mediawiki_dir: ${target_mediawiki_dir}"
   debug "tmp_dir: ${tmp_dir}"
+
+  [[ -z ${post_installation_examples_dir} ]] && post_installation_examples_dir=$(pwd)
+  debug "post_installation_examples_dir: ${post_installation_examples_dir}"
 
   ensure-root
 
@@ -83,8 +91,8 @@ function restore-mediawiki() {
   dropped_skins_SEPARATOR_dropped_extensions=$(restore-local-settings "${backup_dir}" "${target_mediawiki_dir}") || exit 1
   restore-image-files "${backup_dir}" "${target_mediawiki_dir}"
   restore-certificates-and-keys "${backup_dir}"
-  manual-post-install-warning "${backup_dir}" "${target_mediawiki_dir}" \
-    "${dropped_skins_SEPARATOR_dropped_extensions}" "${source_mediawiki_version}" "${target_mediawiki_version}"
+  manual-post-install-warning "${backup_dir}" "${target_mediawiki_dir}" "${dropped_skins_SEPARATOR_dropped_extensions}" \
+    "${source_mediawiki_version}" "${target_mediawiki_version}" "${post_installation_examples_dir}"
 }
 
 #
@@ -402,10 +410,14 @@ function manual-post-install-warning() {
   local dropped_skins_SEPARATOR_dropped_extensions=$3
   local source_mediawiki_version=$4
   local target_mediawiki_version=$5
+  local post_installation_examples_dir=$6
+
   [[ -z ${backup_dir} ]] && fail "'backup_dir' not provided"
   [[ -z ${target_mediawiki_dir} ]] && fail "'target_mediawiki_dir' not provided"
   [[ -z ${source_mediawiki_version} ]] && fail "'source_mediawiki_version' not provided"
   [[ -z ${target_mediawiki_version} ]] && fail "'target_mediawiki_version' not provided"
+  [[ -z ${post_installation_examples_dir} ]] && fail "'post_installation_examples_dir' not provided"
+  [[ -d ${post_installation_examples_dir} ]] || fail "'post_installation_examples_dir' not a valid directory: ${post_installation_examples_dir}"
   info ""
   info ""
   local dropped_skins=${dropped_skins_SEPARATOR_dropped_extensions%${SEPARATOR}*}
@@ -413,8 +425,14 @@ function manual-post-install-warning() {
   local dropped_extensions=${dropped_skins_SEPARATOR_dropped_extensions#*${SEPARATOR}}
   [[ -n ${dropped_extensions} ]] && info "commented out extensions: ${dropped_extensions}" || info "no extensions were commented out"
 
+  #
+  # copy examples
+  #
+  cp ${backup_dir}/etc/httpd/conf.d/ssl.conf ${post_installation_examples_dir} || \
+    fail "failed to copy ${backup_dir}/etc/httpd/conf.d/ssl.conf in ${post_installation_examples_dir}"
+
   local listen_directive
-  listen_directive=$(cat ${backup_dir}/etc/httpd/conf.d/ssl.conf | grep "^Listen")
+  listen_directive=$(cat ${post_installation_examples_dir}/ssl.conf | grep "^Listen")
 
   info ""
   info ""
@@ -423,8 +441,8 @@ function manual-post-install-warning() {
   if [[ ${source_mediawiki_version} != "${target_mediawiki_version}" ]]; then
       warn " 1. This MediaWiki version (${target_mediawiki_version}) is different from source version (${source_mediawiki_version}), run php update in ${target_mediawiki_dir}/maintenance"
   fi
-  warn " 2. configure the Listen directive and the virtual host in /etc/httpd/conf.d/ssl.conf to \"${listen_directive}\""
-  warn " - update custom configurations from the backup php.ini into /etc/php.ini"
+  warn " 2. Configure the Listen directive and the virtual host in /etc/httpd/conf.d/ssl.conf to \"${listen_directive}\""
+  warn " 3. Update custom configurations from the backup php.ini into /etc/php.ini"
   [[ -n ${dropped_extensions} ]] && warn " - re-install the following extensions: ${dropped_extensions}"
   info ""
 }
