backup-RackStationB-active-initiated (2)

diff --git a/backup-RackStationB-active-initiated b/backup-RackStationB-active-initiated
--- a/backup-RackStationB-active-initiated
+++ b/backup-RackStationB-active-initiated
@@ -1,15 +1,19 @@
 #!/bin/bash
 
-FILESYSTEMS_TO_BACKUP="\
-/volume1/base \
-/volume1/dovecot \
-/volume1/jspwiki \
-/volume1/timesnap \
-/volume2/livingroom \
-/volume3/projects \
-/volume4/backups"
+#FILESYSTEMS_TO_BACKUP="\
+#/volume1/base \
+#/volume1/dovecot \
+#/volume1/jspwiki \
+#/volume1/timesnap \
+#/volume2/livingroom \
+#/volume3/projects \
+#/volume4/backups"
 
-LOCAL_RACKSTATIONB_MOUNT_POINT=/rackstationb
+FILESYSTEMS_TO_BACKUP="\
+/volume1/timesnap"
+
+
+BACKUP_NODE_MOUNT_POINT=/rackstationb
 
 function display_help() {
 
@@ -46,12 +50,12 @@ function main() {
         shift
     done
 
-    [ -z "${backup_node_address}" ] && { echo "backup node address not provided. Set it as value of BACKUP_NODE_ADDRESS environment variable or with --address=... command line parameter" 1>&2; exit 1; }
-    [ -z "${backup_node_port}" ] && { echo "backup node port not provided. Set it as value of BACKUP_NODE_PORT environment variable or with --port=... command line parameter" 1>&2; exit 1; }
+    [ -z "${backup_node_address}" ] && { echo "[error]: backup node address not provided. Set it as value of BACKUP_NODE_ADDRESS environment variable or with --address=... command line parameter" 1>&2; exit 1; }
+    [ -z "${backup_node_port}" ] && { echo "[error]: backup node port not provided. Set it as value of BACKUP_NODE_PORT environment variable or with --port=... command line parameter" 1>&2; exit 1; }
 
-#    for i in ${FILESYSTEMS_TO_BACKUP}; do
-#        backup-filesystem ${i} || echo "failed to backup filesystem ${i}" 1>&2;
-#    done
+    for i in ${FILESYSTEMS_TO_BACKUP}; do
+        backup-filesystem ${i} || echo "failed to backup filesystem ${i}" 1>&2;
+    done
 }
 
 function backup-filesystem() {
@@ -60,10 +64,12 @@ function backup-filesystem() {
 
     echo "backing up ${rackstation_filesystem} ..."
 
+    return 0
+
     local volume_dir=${rackstation_filesystem/\//}
     volume_dir=${volume_dir%%/*}
 
-    local local_dir=${LOCAL_RACKSTATIONB_MOUNT_POINT}/${volume_dir}
+    local local_dir=${BACKUP_NODE_MOUNT_POINT}/${volume_dir}
 
     if [ ! -d ${local_dir} ]; then
 
