automated backup routine

diff --git a/backup-RackStationB b/backup-RackStationB
--- a/backup-RackStationB
+++ b/backup-RackStationB
@@ -1,5 +1,23 @@
 #!/bin/bash
 
+#FILESYSTEMS_TO_BACKUP="\
+#/volume1/base \
+#/volume1/dovecot \
+#/volume1/jspwiki \
+#/volume1/timesnap \
+#/volume2/livingroom \
+#/volume3/projects \
+#/volume4/backups"
+
+FILESYSTEMS_TO_BACKUP="\
+/volume1/jspwiki \
+/volume1/timesnap \
+/volume4/backups"
+
+RACKSTATION_IP=192.168.1.2
+
+LOCAL_RACKSTATIONB_MOUNT_POINT=/rackstationb
+
 #[ -d /Volumes/base ] || { echo "/Volumes/base not mounted" 1>&2; exit 1; }
 #[ -d /Volumes/livingroom ] || { echo "/Volumes/livingroom not mounted" 1>&2; exit 1; }
 #[ -d /Volumes/RackStationB ] || { echo "The target USB drive was not mounted" 1>&2; exit 1; }
@@ -18,8 +36,30 @@ EOF
 }
 function main() {
 
-
+    for i in ${FILESYSTEMS_TO_BACKUP}; do
+        backup-filesystem ${i} || echo "failed to backup filesystem ${i}" 1>&2;
+    done
 }
 
+function backup-filesystem() {
+
+    local rackstation_filesystem=$1
+
+    echo "backing up ${rackstation_filesystem} ..."
+
+    local volume_dir=${rackstation_filesystem/\//}
+    volume_dir=${volume_dir%%/*}
+
+    local local_dir=${LOCAL_RACKSTATIONB_MOUNT_POINT}/${volume_dir}
+
+    if [ ! -d ${local_dir} ]; then
+
+        mkdir ${local_dir} || { echo "failed to create directory ${local_dir}" 1>&2; return 1; }
+
+    fi
+
+    rsync -avzhe ssh --rsync-path=/usr/syno/bin/rsync root@${RACKSTATION_IP}:${rackstation_filesystem} ${local_dir} && echo "${rackstation_filesystem} ok"
+
+}
 main "$@"
 
